version: '3.12'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    expose:
      - '8052'
    env_file:
      - .env # This will load variables from .env
    # Or specify individual environment variables:
    # environment:
    #   - DATABASE_URL=postgres://user:pass@db:5432/dbname
    #   - SECRET_KEY=your_secret_key

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - '0.0.0.0:8052:80'
    networks:
      - default
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
